name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip zlib1g-dev libltdl-dev libffi-dev libssl-dev
          pip install --user --upgrade buildozer Cython==0.29.33
      - run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug
